harvester/harvester-ui

.drone.yml, package.json, scripts/clean, test/utils/array.js, test/utils/object.js
=> Add harvester-ui Drone CI

.drone.yml, README.md, config/footer.js, package.json
=> update readme and scripts

assets/translations/en-us.yaml, detail/kubevirt.io.virtualmachine/annotations-modal/index.vue, detail/kubevirt.io.virtualmachine/description-modal/index.vue, detail/kubevirt.io.virtualmachine/index.vue, detail/kubevirt.io.virtualmachine/labels-modal/index.vue, detail/kubevirt.io.virtualmachine/resource-state/index.vue, detail/kubevirt.io.virtualmachine/tabs/details/index.vue, detail/kubevirt.io.virtualmachine/tabs/disks/index.vue, detail/kubevirt.io.virtualmachine/tabs/environment/index.vue, detail/kubevirt.io.virtualmachine/tabs/events/index.vue, detail/kubevirt.io.virtualmachine/tabs/network-interfaces/index.vue, detail/kubevirt.io.virtualmachine/tabs/overview/details.vue, detail/kubevirt.io.virtualmachine/tabs/overview/events.vue, detail/kubevirt.io.virtualmachine/tabs/overview/index.vue, detail/kubevirt.io.virtualmachine/tabs/overview/utilization.vue
- vm detail main page
- vm detail tabs page
- overview
- details
- events
- vm detail tabs page
- environment
- network interfaces
- disks
=> feat(vm-details-page): add vm details page

detail/kubevirt.io.virtualmachine/annotations-modal/index.vue, detail/kubevirt.io.virtualmachine/description-modal/index.vue, detail/kubevirt.io.virtualmachine/labels-modal/index.vue, detail/kubevirt.io.virtualmachine/tabs/details/index.vue, detail/kubevirt.io.virtualmachine/tabs/overview/details.vue, detail/kubevirt.io.virtualmachine/tabs/overview/index.vue
- update annotations/description/labels from api
- use ipAddress component to display ip address
- set max-height for the event card in overview page
=> fix(vmi/details): update annotations/description/labels from api

components/form/KeyValue.vue, components/form/SerialConsole/index.vue, detail/kubevirt.io.virtualmachine/index.vue, detail/kubevirt.io.virtualmachine/tabs/console/index.vue, models/kubevirt.io.virtualmachineinstance.js
- add serial-console component
- remove watch function of KeyValue.vue
@WuJun2016 
In KeyValue.vue, I removed the monitoring function of value. 
Because it will invalidate the KeyValue component in the VMI detail page.
Please check. Thank you!
在 KeyValue.vue中，我移除了value的监听函数。
因为这会导致VMI详情页中的KeyValue组件失效。
请检查一下我是否可以移除该函数，谢谢！
=> feat(serial-console): add serial-console component

detail/kubevirt.io.virtualmachine/tabs/details/basics.vue, detail/kubevirt.io.virtualmachine/tabs/details/index.vue
=> fix(vmi-details): move status panel to left

components/nav/Header.vue, detail/kubevirt.io.virtualmachine/tabs/details/index.vue
- #### merge status panel to basics panel
- #### change "Rancher" to "Harvester"
=> fix(vmi-details): merge status panel to basics panel

components/form/Console.vue, components/form/ConsoleBar.vue, components/form/SerialConsole/index.vue, pages/console/_uid/serial.vue, pages/console/_uid/vnc.vue
=> feat(web-console): open new window to display web-console

assets/translations/en-us.yaml, detail/kubevirt.io.virtualmachine/tabs/details/basics.vue, detail/kubevirt.io.virtualmachine/tabs/details/configurations.vue, detail/kubevirt.io.virtualmachine/tabs/details/index.vue, detail/kubevirt.io.virtualmachine/tabs/events/index.vue
=> fix(configurations): if the object is empty code still working

assets/styles/themes/_light.scss, components/form/AddSSHKey.vue, components/form/ConsoleBar.vue, components/form/VMModal.vue, edit/kubevirt.io.virtualmachine/ChooseImage.vue, edit/kubevirt.io.virtualmachine/index.vue, list/kubevirt.io.virtualmachine.vue
- update VM create page style
- add console-bar at VM list
- cover proxy mode
=> feat(vmi): update page style

assets/styles/themes/_light.scss, components/ResourceDetail/Masthead.vue, components/form/ConsoleBar.vue, components/form/SerialConsole/index.vue, detail/kubevirt.io.virtualmachine/annotations-modal/index.vue, detail/kubevirt.io.virtualmachine/description-modal/index.vue, detail/kubevirt.io.virtualmachine/index.vue, detail/kubevirt.io.virtualmachine/labels-modal/index.vue, pages/console/_uid/serial.vue, pages/console/_uid/vnc.vue
- only display VM state
- close modal after clicking save button
- events sync realtime
- update SerialConsole style and VNC style
=> fix(ConsoleBar): cover edge cases & updat style

detail/harvester.cattle.io.virtualmachineimage.vue, edit/harvester.cattle.io.keypair.vue, edit/harvester.cattle.io.virtualmachineimage.vue
- update keypair page style
- update image page style
=> fix(vm-pages): update page style

components/form/KeyValue.vue, detail/kubevirt.io.virtualmachine/tabs/details/configurations.vue
[https://github.com/rancher/harvester/issues/89](https://github.com/rancher/harvester/issues/89)
=> fix(KeyValue): clean up bound object when the rows is empty

assets/styles/global/_labeled-input.scss, components/DetailTop.vue, components/ResourceDetail/Masthead.vue, components/YamlEditor.vue, detail/harvester.cattle.io.virtualmachineimage.vue, edit/harvester.cattle.io.virtualmachineimage.vue, edit/kubevirt.io.virtualmachine/index.vue
[https://github.com/rancher/harvester/issues/95](https://github.com/rancher/harvester/issues/95)
=> fix(vm-image-details): fix bug

components/PromptRemove.vue, components/SortableTable/selectionStore.js, config/table-headers.js, plugins/steve/actions.js, plugins/steve/resource-instance.js, store/action-menu.js, store/listeners.js
- fix bug
- support sort by state
- support batch rush delete (pass the confirm modal)
[https://github.com/rancher/harvester/issues/97](https://github.com/rancher/harvester/issues/97)
=> fix(vm-image-list): fix bug & support sort by state & batch rush delete

components/form/ConsoleBar.vue
=> update console text and size

detail/kubevirt.io.virtualmachine/resource-state/index.vue, detail/kubevirt.io.virtualmachine/tabs/details/events.vue, detail/kubevirt.io.virtualmachine/tabs/events/index.vue, edit/harvester.cattle.io.keypair.vue, models/harvester.cattle.io.virtualmachineimage.js
- if image is failed status disable to create vm from image
- fix(keypair-edit): show name only when editing the form
- feat(vm-detail-events): display event type
[https://github.com/rancher/harvester/issues/97](https://github.com/rancher/harvester/issues/97)
[https://github.com/rancher/harvester/issues/104](https://github.com/rancher/harvester/issues/104)
=> fix(detail-pages): fix bug

components/PromptRemove.vue, detail/kubevirt.io.virtualmachine/tabs/events/index.vue, store/action-menu.js
- feat(PromptRemove): remove rush batch delete mode
- fix(vm-events): update style
=> feat(PromptRemove): remove rush batch delete mode

components/YamlEditor.vue
[https://github.com/rancher/harvester/issues/100](https://github.com/rancher/harvester/issues/100)
=> fix(YamlEditor): Read from File only accept .yml,.yaml now

components/PromptRemove.vue, detail/kubevirt.io.virtualmachine/tabs/details/configurations.vue, detail/kubevirt.io.virtualmachine/tabs/events/index.vue
- show api on new page when clicking resource name on promptRemove
- remove field of template on configuration panel
- remove vmi name on events panel
[https://github.com/rancher/harvester/issues/102](https://github.com/rancher/harvester/issues/102)
=> fix(PromptRemove): show api on new page

components/form/AddSSHKey.vue, components/form/SSHKeysBar.vue, edit/kubevirt.io.virtualmachine/index.vue
- fix the state of the selelct all checkbox
- update comparison rule
=> fix(SSHKeysBar): update comparison rule

components/nav/Header.vue, middleware/authenticated.js, pages/prefs.vue, store/prefs.js
- only support light theme
- update avatar style
- use virtual defaults instead of explorer in route
[https://github.com/rancher/harvester/issues/131](https://github.com/rancher/harvester/issues/131)
=> fix(prefs): only support light theme

components/PromptRemove.vue, detail/kubevirt.io.virtualmachine/tabs/details/configurations.vue
[https://github.com/rancher/harvester/issues/102](https://github.com/rancher/harvester/issues/102)
=> fix(PromptRemove.vue): cover proxy mode cases

edit/kubevirt.io.virtualmachine/index.vue, mixins/vm.js
https://github.com/rancher/harvester/issues/136
=> feature(cloud-init enchancement)

components/form/ConsoleBar.vue, edit/kubevirt.io.virtualmachine/ChooseImage.vue
- support pagination
- refactor component ConsoleBar.vue
=> feat(ChooseImage.vue): support pagination

edit/cdi.kubevirt.io.datavolume/VolumeSource.vue, edit/harvester.cattle.io.virtualmachinetemplate/index.vue
[https://github.com/rancher/harvester/issues/137](https://github.com/rancher/harvester/issues/137)
=> fix(virtualmachinetemplate/index.vue): update format of fields

components/formatter/volumesState.vue, config/labels-annotations.js, detail/cdi.kubevirt.io.datavolume.vue, detail/harvester.cattle.io.virtualmachinetemplate/details.vue, detail/harvester.cattle.io.virtualmachinetemplate/index.vue, detail/kubevirt.io.virtualmachine/tabs/details/basics.vue, edit/kubevirt.io.virtualmachine/ChooseImage.vue, edit/kubevirt.io.virtualmachine/index.vue, mixins/vm.js, models/harvester.cattle.io.virtualmachinetemplateversion.js
[https://github.com/rancher/harvester/issues/101](https://github.com/rancher/harvester/issues/101)
[https://github.com/rancher/harvester/issues/137](https://github.com/rancher/harvester/issues/137)
- update display logic
- find owner by annotation
- update pagination style
- hide the image field if source is blank
=> fix(anno): update display logic

components/formatter/BadgeStatus.vue, edit/harvester.cattle.io.virtualmachineimage.vue, edit/kubevirt.io.virtualmachine/index.vue, list/harvester.cattle.io.keypair.vue, list/harvester.cattle.io.virtualmachineimage.vue, mixins/create-edit-view.js, plugins/steve/resource-instance.js
https://github.com/rancher/harvester/issues/149
https://github.com/rancher/harvester/issues/152
https://github.com/rancher/harvester/issues/155
=> fix(vm、#149 #155 、multiple vm websocket)

components/form/NetworkModal.vue, components/form/PortInput.vue, components/form/PortInputGroup.vue, mixins/vm.js
[https://github.com/rancher/harvester/issues/129](https://github.com/rancher/harvester/issues/129)
=> feat(NetworkModal.vue): add ports configuration

components/form/ResourceTabs/index.vue, edit/cdi.kubevirt.io.datavolume/index.vue
[https://github.com/rancher/harvester/issues/107](https://github.com/rancher/harvester/issues/107)
[https://github.com/rancher/harvester/issues/164](https://github.com/rancher/harvester/issues/164)
=> fix(datavolume/index.vue): fix Volume Page bug

assets/styles/base/_helpers.scss, assets/styles/base/_typography.scss, components/form/DiskModal.vue, edit/harvester.cattle.io.virtualmachinetemplate/index.vue, edit/kubevirt.io.virtualmachine/ChooseImage.vue, edit/kubevirt.io.virtualmachine/index.vue, plugins/steve/resource-instance.js
https://github.com/rancher/harvester/issues/105
https://github.com/rancher/harvester/issues/160
=> fix(#105 #160)

plugins/steve/subscribe.js
https://github.com/rancher/harvester/issues/43
=> fix websocket

assets/translations/en-us.yaml, components/PromptRemove.vue
[https://github.com/rancher/harvester/issues/153](https://github.com/rancher/harvester/issues/153)
=> fix(PromptRemove.vue): fix #153

components/form/DiskModal.vue, components/formatter/EjectCdRow.vue, detail/kubevirt.io.virtualmachine/tabs/details/inventory.vue, mixins/vm.js, models/kubevirt.io.virtualmachineinstance.js, plugins/steve/resource-instance.js
https://github.com/rancher/harvester/issues/123
=> feat(#123)

assets/translations/en-us.yaml, pages/auth/login.vue
[https://github.com/rancher/harvester/issues/132](https://github.com/rancher/harvester/issues/132)
=> feat(Login): add kubeconfig limitation tip

components/formatter/ImagePercentageBar.vue
[https://github.com/rancher/harvester/issues/148](https://github.com/rancher/harvester/issues/148)
=> fix(ImagePercentageBar.vue): fix #148

components/form/FileSelector.vue, detail/kubevirt.io.virtualmachine/annotations-modal/index.vue, detail/kubevirt.io.virtualmachine/tabs/details/configurations.vue, edit/harvester.cattle.io.keypair.vue, pages/auth/login.vue
[https://github.com/rancher/harvester/issues/177](https://github.com/rancher/harvester/issues/177)
[https://github.com/rancher/harvester/issues/197](https://github.com/rancher/harvester/issues/197)
[https://github.com/rancher/harvester/issues/154](https://github.com/rancher/harvester/issues/154)
=> fix #154 #197 #177

pages/auth/login.vue
[https://github.com/rancher/harvester/issues/197](https://github.com/rancher/harvester/issues/197)
=> fix(login.vue): If 500 internal server error, display error message

pages/auth/login.vue, store/auth.js
[https://github.com/rancher/harvester/issues/200](https://github.com/rancher/harvester/issues/200)
=> feat(Login): support local mode

detail/kubevirt.io.virtualmachine/tabs/details/inventory.vue
[https://github.com/rancher/harvester/issues/207](https://github.com/rancher/harvester/issues/207)
=> fix(inventory.vue): Fix typo

assets/translations/en-us.yaml, components/PromptRemove.vue, components/form/SSHKeysBar.vue, components/formatter/ImagePercentageBar.vue, detail/kubevirt.io.virtualmachine/annotations-modal/index.vue, detail/kubevirt.io.virtualmachine/tabs/details/index.vue
[https://github.com/rancher/harvester/issues/177](https://github.com/rancher/harvester/issues/177)
[https://github.com/rancher/harvester/issues/215](https://github.com/rancher/harvester/issues/215)
=> Fix typo & Fix keypairs display bug

assets/translations/en-us.yaml, config/product/virtual.js, detail/harvester.cattle.io.keypair.vue, detail/node/Monitor.vue, detail/node/basic.vue, detail/node/index.vue, detail/node/instance.vue, list/node.vue, models/node.js
- Add host page
- Fix key-pairs page bug [https://github.com/rancher/harvester/issues/220](https://github.com/rancher/harvester/issues/220)
=> Add host page

detail/harvester.cattle.io.virtualmachineimage.vue, edit/harvester.cattle.io.virtualmachineimage.vue
[https://github.com/rancher/harvester/issues/223](https://github.com/rancher/harvester/issues/223)
=> Can input Virtual Machine Image description now

components/ModalWithCard.vue, detail/kubevirt.io.virtualmachine/tabs/details/inventory.vue, detail/kubevirt.io.virtualmachine/tabs/migration/index.vue, edit/kubevirt.io.virtualmachine/index.vue, plugins/steve/actions.js
https://github.com/rancher/harvester/issues/226
https://github.com/rancher/harvester/issues/75
=> fix: (#226 #75)

assets/translations/en-us.yaml, components/formatter/ImagePercentageBar.vue, detail/kubevirt.io.virtualmachine/index.vue, detail/node/basic.vue, detail/node/index.vue, edit/cdi.kubevirt.io.datavolume/index.vue, edit/harvester.cattle.io.virtualmachineimage.vue, list/node.vue
[https://github.com/rancher/harvester/issues/223](https://github.com/rancher/harvester/issues/223)
=> Events filter & Host stroage size & Annotations

components/CopyToClipboardText.vue, components/formatter/HostRoles.vue, list/node.vue
[https://github.com/rancher/harvester/issues/225](https://github.com/rancher/harvester/issues/225)
=> Improve host roles condition & Fix tooltip

components/PromptRemove.vue, promptRemove/kubevirt.io.virtualmachine.vue, store/type-map.js
https://github.com/rancher/harvester/issues/69
=> feat: (allow persist data volume when delete the VM)

detail/kubevirt.io.virtualmachine/tabs/details/inventory.vue
https://github.com/rancher/harvester/issues/233
=> fix: delete cdrow enhancement

components/nav/PureHeader.vue, config/product/virtual.js, list/cdi.kubevirt.io.datavolume.vue
[https://github.com/rancher/harvester-ui/issues/172](https://github.com/rancher/harvester-ui/issues/172)
=> Fix #172 & Remove Volumes list ns switcher

components/form/AddSSHKey.vue, components/formatter/ImagePercentageBar.vue, config/product/virtual.js
[https://github.com/rancher/harvester-ui/issues/199](https://github.com/rancher/harvester-ui/issues/199)
[https://github.com/rancher/harvester/issues/180](https://github.com/rancher/harvester/issues/180)
[https://github.com/rancher/harvester-ui/issues/191](https://github.com/rancher/harvester-ui/issues/191)
=> Fix #180 #199 #191

edit/cdi.kubevirt.io.datavolume/VolumeSource.vue, edit/cdi.kubevirt.io.datavolume/index.vue, store/action-menu.js
- Save ImageId at vm image annotations
- Remove extra divider on ActionMenu
=> Remove extra divider

assets/translations/en-us.yaml, components/form/DiskModal.vue, components/form/NetworkModal.vue, components/formatter/ipAddress.vue, components/formatter/volumesState.vue, config/labels-annotations.js, config/query-params.js, edit/cdi.kubevirt.io.datavolume/VolumeSource.vue, edit/harvester.cattle.io.virtualmachinetemplate/index.vue, edit/k8s.cni.cncf.io.networkattachmentdefinition.vue, edit/kubevirt.io.virtualmachine/index.vue, mixins/create-edit-view.js, mixins/vm.js, models/cdi.kubevirt.io.datavolume.js, models/k8s.cni.cncf.io.networkattachmentdefinition.js, models/kubevirt.io.virtualmachine.js, plugins/steve/mutations.js
https://github.com/rancher/harvester/issues/241
https://github.com/rancher/harvester/issues/234
=> fix: #241, #234, feat: network

config/product/virtual.js
[https://github.com/rancher/harvester-ui/issues/199](https://github.com/rancher/harvester-ui/issues/199)
=> Fix wrong order

components/PromptRemove.vue, components/form/NetworkModal.vue, mixins/vm.js, pages/c/_cluster/virtual/index.vue, promptRemove/kubevirt.io.virtualmachine.vue
https://github.com/rancher/harvester/issues/69
=> fix: promptRemove style,  font info

edit/kubevirt.io.virtualmachine/index.vue, list/k8s.cni.cncf.io.networkattachmentdefinition.vue, mixins/vm.js
https://github.com/rancher/harvester-ui/issues/214
https://github.com/rancher/harvester-ui/issues/212
=> fix: 212 214

components/form/SSHKeysBar.vue, config/labels-annotations.js, detail/kubevirt.io.virtualmachine/tabs/events/index.vue, edit/kubevirt.io.virtualmachine/index.vue
[https://github.com/rancher/harvester/issues/176](https://github.com/rancher/harvester/issues/176)
=> Use annotation to filter keypairs

components/formatter/ipAddress.vue, config/labels-annotations.js, edit/kubevirt.io.virtualmachine/index.vue, models/kubevirt.io.virtualmachine.js
https://github.com/rancher/harvester-ui/issues/223
=> feat: #223

components/form/ConsoleBar.vue, models/cdi.kubevirt.io.datavolume.js, store/action-menu.js
[https://github.com/rancher/harvester/issues/198](https://github.com/rancher/harvester/issues/198)
[https://github.com/rancher/harvester-ui/issues/215](https://github.com/rancher/harvester-ui/issues/215)
[https://github.com/rancher/harvester/issues/224](https://github.com/rancher/harvester/issues/224)
=> #198 & #215 & #224

components/PromptRemove.vue, detail/kubevirt.io.virtualmachine/tabs/details/basics.vue, models/cdi.kubevirt.io.datavolume.js
[https://github.com/rancher/harvester-ui/issues/231](https://github.com/rancher/harvester-ui/issues/231)
[https://github.com/rancher/harvester/issues/198](https://github.com/rancher/harvester/issues/198)
=> Fix #198 & #231

edit/kubevirt.io.virtualmachine/volume/type/existing.vue, mixins/vm.js
#link 
https://github.com/rancher/harvester/issues/263
=> fix: existing volume

components/EjectCDROM/index.vue, models/kubevirt.io.virtualmachine.js
#link 
https://github.com/rancher/harvester/issues/281
=> fix: 281, eject-cdrom-style

assets/translations/en-us.yaml, components/formatter/HostCustomName.vue, config/labels-annotations.js, detail/node/basic.vue, edit/node.vue, list/node.vue, models/node.js
[https://github.com/rancher/harvester-ui/issues/200](https://github.com/rancher/harvester-ui/issues/200)
=> Add Host Edit Page

components/form/FileSelector.vue, detail/harvester.cattle.io.setting/index.vue, edit/harvester.cattle.io.setting/index.vue, models/harvester.cattle.io.setting.js, pages/auth/login.vue, store/auth.js
[https://github.com/rancher/harvester/issues/290](https://github.com/rancher/harvester/issues/290)
[https://github.com/rancher/harvester/issues/154](https://github.com/rancher/harvester/issues/154)
=> Add edit setting page & add accept file type for FileSelector

pages/console/_uid/serial.vue, pages/console/_uid/vnc.vue
[https://github.com/rancher/harvester-ui/issues/228](https://github.com/rancher/harvester-ui/issues/228)
=> make the window title consistent with vm name

components/DetailTop.vue, config/labels-annotations.js, edit/cdi.kubevirt.io.datavolume/index.vue, edit/harvester.cattle.io.user.vue, edit/harvester.cattle.io.virtualmachineimage.vue, edit/k8s.cni.cncf.io.networkattachmentdefinition.vue, models/cdi.kubevirt.io.datavolume.js, models/harvester.cattle.io.virtualmachineimage.js, utils/custom-validators.js, utils/validators/vm-image.js
[https://github.com/rancher/harvester-ui/issues/273](https://github.com/rancher/harvester-ui/issues/273)
- Labels Enhancement
- Hide annotations
- Use CruResource
- VM Image custom validations
=> Labels Enhancement

models/cdi.kubevirt.io.datavolume.js, utils/custom-validators.js, utils/validators/vm-datavolumes.js
[https://github.com/rancher/harvester/issues/302](https://github.com/rancher/harvester/issues/302)
=> Volume size must be integer

components/nav/PureHeader.vue, detail/harvester.cattle.io.setting/index.vue, detail/harvester.cattle.io.user.vue, detail/harvester.cattle.io.virtualmachinetemplateversion/index.vue, detail/k8s.cni.cncf.io.networkattachmentdefinition.vue, detail/node/index.vue, edit/cdi.kubevirt.io.datavolume/index.vue, edit/harvester.cattle.io.user.vue, edit/harvester.cattle.io.virtualmachineimage.vue, edit/harvester.cattle.io.virtualmachinetemplateversion/index.vue, edit/k8s.cni.cncf.io.networkattachmentdefinition.vue, edit/kubevirt.io.virtualmachine/index.vue, edit/node.vue, models/cdi.kubevirt.io.datavolume.js, models/harvester.cattle.io.virtualmachineimage.js, store/auth.js
- Use Tabbed to display Edit Page
- Refactor by annotationsToIgnoreRegexes
- Tab Label Polish
- Keep avatar consistent with username
=> Refactor by annotationsToIgnoreRegexes

edit/harvester.cattle.io.virtualmachineimage.vue, utils/validators/vm-image.js
[https://github.com/rancher/harvester/issues/323](https://github.com/rancher/harvester/issues/323)
=> convert file suffic of image to lower case

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, config/table-headers.js, detail/cdi.kubevirt.io.datavolume.vue, detail/harvester.cattle.io.user.vue, detail/harvester.cattle.io.virtualmachineimage.vue, edit/cdi.kubevirt.io.datavolume/basic.vue, edit/harvester.cattle.io.keypair.vue, edit/harvester.cattle.io.user.vue, edit/harvester.cattle.io.virtualmachineimage.vue, list/cdi.kubevirt.io.datavolume.vue, list/harvester.cattle.io.keypair.vue, list/harvester.cattle.io.virtualmachineimage.vue, models/harvester.cattle.io.virtualmachineimage.js, pages/auth/login.vue
=> Update Chinese Simplified Translation

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, components/nav/PureHeader.vue, detail/cdi.kubevirt.io.datavolume.vue, edit/cdi.kubevirt.io.datavolume/basic.vue, edit/harvester.cattle.io.virtualmachineimage.vue, pages/auth/login.vue, utils/validators/vm-image.js
=> Header translation and Volume translation

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, components/nav/PureHeader.vue, pages/auth/login.vue
- update login page translation
- add the min-width of preferences popover
=> add the min-width of preferences popover

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, components/form/AddSSHKey.vue, components/form/DiskModal.vue, components/form/NetworkModal.vue, edit/kubevirt.io.virtualmachine/SSHKey.vue, models/cdi.kubevirt.io.datavolume.js, utils/validators/vm-datavolumes.js, utils/validators/vm-image.js, utils/validators/vm.js
=> Update translation of VM validation

detail/harvester.cattle.io.virtualmachinetemplateversion/index.vue, detail/kubevirt.io.virtualmachine/tabs/details/basics.vue
https://github.com/rancher/harvester-ui/issues/308
=> add chinese Simplifed Translation

assets/translations/zh-hans.yaml
=> Update translation of Volume page and Login page

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, components/Loading.vue, components/nav/Footer.vue, detail/node/basic.vue, pages/auth/login.vue
=> Add switch locale component on Login page

plugins/axios.js, store/auth.js
[https://github.com/rancher/harvester/issues/304](https://github.com/rancher/harvester/issues/304)
=> Add timeout to global config of axios

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, plugins/axios.js
[https://github.com/rancher/harvester/issues/304](https://github.com/rancher/harvester/issues/304)
=> Update timeout error message

edit/kubevirt.io.virtualmachine/CpuMemory.vue
[https://github.com/rancher/harvester/issues/370](https://github.com/rancher/harvester/issues/370)
=> Memory field of VM Edit Form would be always converted to Gb

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, components/form/ConsoleBar.vue, utils/validators/vm.js
[https://github.com/rancher/harvester/issues/305](https://github.com/rancher/harvester/issues/305)
=> Name of the vm volume will be displayed when the edit form is invalid

components/SortableTable/index.vue, models/kubevirt.io.virtualmachine.js
[https://github.com/rancher/harvester/issues/334](https://github.com/rancher/harvester/issues/334)
=> Add External Buttons Of Table

edit/harvester.cattle.io.virtualmachinetemplateversion/index.vue, edit/kubevirt.io.virtualmachine/index.vue
[https://github.com/rancher/harvester/issues/347](https://github.com/rancher/harvester/issues/347)
=> VM/VM Template should not support yaml mode when editing

list/harvester.cattle.io.virtualmachineimage.vue, utils/poller.js
https://github.com/rancher/harvester/issues/336
=> feat: #336

components/ConsumptionGauge.vue, components/nav/Footer.vue, detail/node/basic.vue, pages/auth/login.vue
https://github.com/rancher/harvester/issues/430
delete None item in language
https://github.com/rancher/harvester/issues/402
=> fix (Incorrect storage size) #430

edit/harvester.cattle.io.virtualmachinetemplateversion/index.vue, scripts/build-embedded
https://github.com/rancher/harvester/issues/428
=> fix: template catch err, #428

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, edit/kubevirt.io.virtualmachine/index.vue, mixins/vm.js
https://github.com/rancher/harvester/issues/417
=> feat: #417

components/NovncConsole.vue, components/form/Console.vue
[https://github.com/rancher/harvester/issues/401](https://github.com/rancher/harvester/issues/401)
add `Print Screen` `Ctrl Alt Delete` shortkeys
=> Add NoVNC ShortKeys

components/NovncConsole.vue, components/form/Console.vue
[https://github.com/rancher/harvester/issues/401](https://github.com/rancher/harvester/issues/401)
=> Add Ctrl Combinations Keys

components/InputOrDisplay.vue, detail/cdi.kubevirt.io.datavolume.vue, detail/harvester.cattle.io.keypair.vue, detail/harvester.cattle.io.setting/NetworkSetting.vue, detail/harvester.cattle.io.setting/index.vue, detail/harvester.cattle.io.user.vue, detail/harvester.cattle.io.virtualmachineimage.vue, detail/k8s.cni.cncf.io.networkattachmentdefinition.vue, detail/kubevirt.io.virtualmachine/tabs/details/basics.vue, edit/kubevirt.io.virtualmachine/CpuMemory.vue, edit/kubevirt.io.virtualmachine/Image.vue, edit/kubevirt.io.virtualmachine/SSHKey.vue, edit/kubevirt.io.virtualmachine/network/base.vue, edit/kubevirt.io.virtualmachine/volume/type/container.vue, edit/kubevirt.io.virtualmachine/volume/type/existing.vue, edit/kubevirt.io.virtualmachine/volume/type/vmImage.vue, edit/kubevirt.io.virtualmachine/volume/type/volume.vue
- implement a new component `InputOrDisplay`
- use LabelValue / InputOrDisplay on detail pages
[https://github.com/rancher/harvester/issues/499](https://github.com/rancher/harvester/issues/499)
=> use LabelValue / InputOrDisplay on detail pages

assets/styles/themes/_green.scss
[https://github.com/rancher/harvester/issues/493](https://github.com/rancher/harvester/issues/493)
=> use darker green to show success status

assets/styles/app.scss, assets/styles/themes/_green-dark.scss
[https://github.com/rancher/harvester/issues/493](https://github.com/rancher/harvester/issues/493)
=> dark green theme

models/kubevirt.io.virtualmachine.js, store/index.js
https://github.com/rancher/harvester/issues/522
=> delete v3/schema api, fix: restore => restoring

components/Notification/main.vue, plugins/steve/actions.js
[https://github.com/rancher/harvester/issues/520](https://github.com/rancher/harvester/issues/520)
=> display notification when the actions throw errors

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, components/ResourceDetail/Masthead.vue, components/Switches.vue, components/formatter/RestoreProgress.vue, components/formatter/vmState.vue, config/labels-annotations.js, config/product/virtual.js, config/types.js, detail/network.harvester.cattle.io.clusternetwork.vue, detail/node/basic.vue, detail/node/index.vue, edit/harvester.cattle.io.setting/NetworkSetting.vue, edit/harvester.cattle.io.virtualmachinebackup.vue, edit/network.harvester.cattle.io.clusternetwork/index.vue, edit/node.vue, list/harvester.cattle.io.setting.vue, list/k8s.cni.cncf.io.networkattachmentdefinition.vue, list/kubevirt.io.virtualmachine/index.vue, models/harvester.cattle.io.virtualmachinebackup.js, models/harvester.cattle.io.virtualmachinerestore.js, models/kubevirt.io.virtualmachine.js, models/longhorn.io.engine.js, models/network.harvester.cattle.io.clusternetwork.js, models/network.harvester.cattle.io.nodenetwork.js, scripts/build-aws, utils/promise.js
https://github.com/rancher/harvester/issues/249
=> feat: network, backup progress

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, plugins/steve/actions.js
[https://github.com/rancher/harvester/issues/520](https://github.com/rancher/harvester/issues/520)
=> cover edge cases

components/formatter/MaintenanceState.vue, config/labels-annotations.js, edit/cdi.kubevirt.io.datavolume/basic.vue, edit/cdi.kubevirt.io.datavolume/index.vue, edit/kubevirt.io.virtualmachine/volume/index.vue, list/kubevirt.io.virtualmachine/index.vue, list/node.vue, mixins/vm.js, models/kubevirt.io.virtualmachine.js, models/node.js
[https://github.com/rancher/harvester/issues/384](https://github.com/rancher/harvester/issues/384)
=> [UI] Add Migration

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, components/formatter/vmState.vue, detail/node/instance.vue, edit/network.harvester.cattle.io.clusternetwork/index.vue, edit/node.vue, list/k8s.cni.cncf.io.networkattachmentdefinition.vue, list/kubevirt.io.virtualmachine/index.vue, models/k8s.cni.cncf.io.networkattachmentdefinition.js, models/kubevirt.io.virtualmachine.js, models/network.harvester.cattle.io.clusternetwork.js
https://github.com/rancher/harvester/issues/557
https://github.com/rancher/harvester/issues/545
https://github.com/rancher/harvester/issues/542
=> Network fix

edit/node.vue
=> fix save network conflict

promptRemove/kubevirt.io.virtualmachine.vue, scripts/build-aws
#link
https://github.com/rancher/harvester/issues/563
=> fix: proxy mode can't remove vm

assets/translations/en-us.yaml, components/nav/PureHeader.vue, edit/harvester.cattle.io.setting/RancherEnabled.vue, edit/harvester.cattle.io.setting/index.vue, edit/harvester.cattle.io.virtualmachineimage.vue, list/harvester.cattle.io.setting.vue
https://github.com/rancher/harvester/issues/513
=> feat: add rancher link on rancher mode

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, edit/harvester.cattle.io.user.vue, list/harvester.cattle.io.user.vue, pages/auth/login.vue, plugins/axios.js, store/auth.js, store/index.js
[https://github.com/rancher/harvester/issues/588](https://github.com/rancher/harvester/issues/588)
=> [UI]Fix proxy mode bugs 

detail/kubevirt.io.virtualmachine/tabs/details/basics.vue, edit/harvester.cattle.io.setting/index.vue, list/kubevirt.io.virtualmachine/backupModal.vue, plugins/steve/actions.js
https://github.com/rancher/harvester/issues/548
https://github.com/rancher/harvester/issues/385
=> fix: 548, setting config page tab error

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, middleware/authenticated.js, pages/auth/login.vue, store/auth.js
[https://github.com/rancher/harvester/issues/513](https://github.com/rancher/harvester/issues/513)
=> [UI] initial server-url and initial the password of admin

store/auth.js
[https://github.com/rancher/harvester/issues/513](https://github.com/rancher/harvester/issues/513)
=> [UI]Set state.isFirstLogin to false after logged in

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, pages/auth/login.vue, plugins/axios.js, store/auth.js
[https://github.com/rancher/harvester/issues/513](https://github.com/rancher/harvester/issues/513)
=> [UI]highlight admin and remove canGetAuthModes condition

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, pages/auth/login.vue
[https://github.com/rancher/harvester/issues/513](https://github.com/rancher/harvester/issues/513)
=> [UI]Login style polish

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, detail/node/index.vue, list/kubevirt.io.virtualmachine/backupModal.vue, list/kubevirt.io.virtualmachine/restoreModal.vue
https://github.com/rancher/harvester/issues/546
https://github.com/rancher/harvester/issues/607
=> fix: 546, 607

components/formatter/MigrationState.vue, components/formatter/nodeName.vue, detail/kubevirt.io.virtualmachine/index.vue, detail/kubevirt.io.virtualmachine/tabs/migration/index.vue
[https://github.com/rancher/harvester/issues/612](https://github.com/rancher/harvester/issues/612)
=> [UI]NodeName computed by the value obtained from vuex

components/SortableTable/THead.vue, components/SortableTable/paging.js
[https://github.com/rancher/harvester/issues/547](https://github.com/rancher/harvester/issues/547)
=> [UI]Use data prop transmit the value changes

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, components/formatter/MigrationState.vue, config/labels-annotations.js, layouts/default.vue, list/kubevirt.io.virtualmachine/MigrationModal.vue, list/kubevirt.io.virtualmachine/index.vue, list/node/index.vue, list/node/maintenanceModal.vue, models/kubevirt.io.virtualmachine.js, models/kubevirt.io.virtualmachineinstance.js, models/node.js, plugins/steve/actions.js, store/action-menu.js, store/kubevirt.io.virtualmachine.js, store/node.js
- add a modal to choose target node for migration
- migration state obtained by `VMI` annotations
- update translations
[https://github.com/rancher/harvester/issues/622](https://github.com/rancher/harvester/issues/622)
[https://github.com/rancher/harvester/issues/643](https://github.com/rancher/harvester/issues/643)
=> [UI]Allow user to choose the target node for migration

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, list/harvester.cattle.io.virtualmachinebackup.vue, models/harvester.cattle.io.setting.js, plugins/steve/subscribe.js, utils/socket.js
https://github.com/rancher/harvester/issues/638
https://github.com/rancher/harvester/issues/653
=> fix: 653,638

detail/harvester.cattle.io.virtualmachinebackup/keypairs.vue, detail/kubevirt.io.virtualmachine/tabs/details/keypairs.vue, edit/kubevirt.io.virtualmachine/index.vue, mixins/vm.js, plugins/steve/subscribe.js
https://github.com/rancher/harvester/issues/640
=> feat: cloud-init configuration enhancement, fix: logout page websocket tip show

list/kubevirt.io.virtualmachine/index.vue, store/index.js
https://github.com/rancher/harvester/issues/638
=> fix: unsubscribe /v3

edit/harvester.cattle.io.setting/log-level.vue
https://github.com/rancher/harvester/issues/656
=> feat: add log level configuration

components/PromptRemove.vue, components/formatter/vmName.vue, list/kubevirt.io.virtualmachine/index.vue, models/kubevirt.io.virtualmachineinstance.js, pages/fail-whale.vue, plugins/steve/actions.js
https://github.com/rancher/harvester/issues/659
https://github.com/rancher/harvester/issues/668
=> fix: 668, 659

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, components/formatter/CloudInitType.vue, config/labels-annotations.js, config/product/virtual.js, detail/configmap.vue, edit/configmap.vue, edit/kubevirt.io.virtualmachine/CloudConfig.vue, edit/kubevirt.io.virtualmachine/index.vue, list/configmap.vue, store/auth.js
[https://github.com/rancher/harvester/issues/523](https://github.com/rancher/harvester/issues/523)
=> implement cloud init

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, edit/kubevirt.io.virtualmachine/CloudConfig.vue, edit/kubevirt.io.virtualmachine/SSHKey.vue, models/kubevirt.io.virtualmachine.js
[https://github.com/rancher/harvester/issues/674](https://github.com/rancher/harvester/issues/674)
[https://github.com/rancher/harvester/issues/517](https://github.com/rancher/harvester/issues/517)
=> [UI]add vm action createTemplate & display sshkeys

components/PercentageBar.vue, components/formatter/RestoreProgress.vue, components/graph/Bar.vue, config/types.js, models/harvester.cattle.io.virtualmachineimage.js, models/harvester.cattle.io.virtualmachinerestore.js, models/kubevirt.io.virtualmachine.js, plugins/steve/subscribe.js
https://github.com/rancher/harvester/issues/683
=> websocket prompt time modification

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, detail/kubevirt.io.virtualmachine/index.vue, detail/kubevirt.io.virtualmachine/tabs/migration/index.vue, detail/node/instance.vue, list/kubevirt.io.virtualmachine/MigrationModal.vue, models/kubevirt.io.virtualmachineinstance.js
[https://github.com/rancher/harvester/issues/693](https://github.com/rancher/harvester/issues/693)
[https://github.com/rancher/harvester/issues/684](https://github.com/rancher/harvester/issues/684)
[https://github.com/rancher/harvester/issues/688](https://github.com/rancher/harvester/issues/688)
[https://github.com/rancher/harvester/issues/643](https://github.com/rancher/harvester/issues/643)
=> fix bugs caused by migration

detail/kubevirt.io.virtualmachine/tabs/details/cloud-configs.vue, detail/kubevirt.io.virtualmachine/tabs/migration/index.vue, models/kubevirt.io.virtualmachine.js
[https://github.com/rancher/harvester/issues/701](https://github.com/rancher/harvester/issues/701)
=> display migration status on the VM detail page

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, components/PercentageBar.vue, edit/kubevirt.io.virtualmachine/volume/index.vue, mixins/vm.js, models/harvester.cattle.io.virtualmachineimage.js
https://github.com/rancher/harvester/issues/694
https://github.com/rancher/harvester/issues/708
=> create iso type vm enhancement, fix: 708

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, components/formatter/vmState.vue, detail/node/instance.vue, edit/kubevirt.io.virtualmachine/CloudConfig.vue, edit/kubevirt.io.virtualmachine/index.vue, list/kubevirt.io.virtualmachine/cloneTemplate.vue, list/kubevirt.io.virtualmachine/index.vue, mixins/vm.js, models/kubevirt.io.virtualmachine.js, store/kubevirt.io.virtualmachine.js
https://github.com/rancher/harvester/issues/702
=> fix: enhancement generate template from vm

mixins/vm.js
https://github.com/rancher/harvester/issues/562
=> fix: USB tablet is enabled default

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, components/EjectCDROM/index.vue, components/NodeConsumptionGauge.vue, components/Tip.vue, components/formatter/CPUUsed.vue, components/formatter/MemoryUsed.vue, components/formatter/StorageUsed.vue, components/formatter/vmState.vue, detail/harvesterhci.io.virtualmachineimage.vue, detail/harvesterhci.io.virtualmachinetemplateversion/index.vue, detail/network.harvesterhci.io.clusternetwork.vue, edit/harvesterhci.io.keypair.vue, edit/harvesterhci.io.setting/backup-target.vue, edit/harvesterhci.io.virtualmachinetemplateversion/index.vue, edit/kubevirt.io.virtualmachine/index.vue, edit/network.harvesterhci.io.clusternetwork/index.vue, layouts/default.vue, list/harvesterhci.io.setting.vue, list/node/index.vue, mixins/vm.js, models/kubevirt.io.virtualmachine.js, pages/fail-whale.vue, scripts/build-embedded, store/index.js, utils/download.js
https://github.com/harvester/harvester/issues/724
https://github.com/harvester/harvester/issues/712
https://github.com/harvester/harvester/issues/736
https://github.com/harvester/harvester/issues/527
https://github.com/harvester/harvester/issues/737
https://github.com/harvester/harvester/issues/743
https://github.com/harvester/harvester/issues/744
=> fix: 724、712、736、527、737、743、744

README.md, config/footer.js, package.json
**Related issue**
harvester/harvester#727
=> fix: update repo reference

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, list/harvesterhci.io.user.vue, list/harvesterhci.io.virtualmachinebackup.vue, list/harvesterhci.io.virtualmachinetemplateversion.vue, list/kubevirt.io.virtualmachine/index.vue, utils/validators/vm-image.js
[https://github.com/harvester/harvester/issues/682](https://github.com/harvester/harvester/issues/682)
[https://github.com/harvester/harvester/issues/742](https://github.com/harvester/harvester/issues/742)
=> compressed image is not supported and display resource list after fetch completed

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, detail/cdi.kubevirt.io.datavolume.vue, edit/cdi.kubevirt.io.datavolume/basic.vue, edit/cdi.kubevirt.io.datavolume/index.vue
[https://github.com/harvester/harvester/issues/746](https://github.com/harvester/harvester/issues/746)
=> fix the display error on the  config tab of the datavolume page

models/harvesterhci.io.virtualmachinetemplate.js, models/k8s.cni.cncf.io.networkattachmentdefinition.js
https://github.com/harvester/harvester/issues/742
=> fix: template list button

components/SortableTable/selectionStore.js
[https://github.com/harvester/harvester/issues/742](https://github.com/harvester/harvester/issues/742)
=> bulk actions are hide by default

assets/translations/en-us.yaml
https://github.com/harvester/harvester/issues/736
=> fix: cout => Count

edit/cdi.kubevirt.io.datavolume/basic.vue, edit/kubevirt.io.virtualmachine/SSHKey.vue
[https://github.com/harvester/harvester/issues/746](https://github.com/harvester/harvester/issues/746)
[https://github.com/harvester/harvester/issues/753](https://github.com/harvester/harvester/issues/753)
=> update ssh-key api url and update label of the image field on data volume page

assets/translations/en-us.yaml, edit/cdi.kubevirt.io.datavolume/basic.vue
[https://github.com/harvester/harvester/issues/746](https://github.com/harvester/harvester/issues/746)
=> update text labels

detail/cdi.kubevirt.io.datavolume.vue, edit/harvesterhci.io.setting/api-ui-source.vue, edit/harvesterhci.io.setting/authentication-mode.vue
[https://github.com/harvester/harvester/issues/756](https://github.com/harvester/harvester/issues/756)
[https://github.com/harvester/harvester/issues/746](https://github.com/harvester/harvester/issues/746)
=> use Select to instead of Input

assets/translations/en-us.yaml, list/kubevirt.io.virtualmachine/index.vue, models/kubevirt.io.virtualmachine.js
https://github.com/harvester/harvester/issues/767
https://github.com/harvester/harvester/issues/769
=> fix: 769, 767

components/form/SerialConsole/index.vue
[https://github.com/harvester/harvester/issues/751](https://github.com/harvester/harvester/issues/751)
=> write into terminal synchronously

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, components/graph/Circle.vue, components/nav/Footer.vue, components/nav/SupportBundle.vue, config/types.js, models/harvesterhci.io.supportbundle.js, store/common.js
https://github.com/harvester/harvester/issues/579
=> feat: support bundle

edit/kubevirt.io.virtualmachine/network/base.vue, edit/kubevirt.io.virtualmachine/network/index.vue
[https://github.com/harvester/harvester/issues/781](https://github.com/harvester/harvester/issues/781)
=> vlan can be duplicated

detail/kubevirt.io.virtualmachine/tabs/events/index.vue, models/kubevirt.io.virtualmachine.js
[https://github.com/harvester/harvester/issues/801](https://github.com/harvester/harvester/issues/801)
=> adjust column width

assets/translations/en-us.yaml, components/ModalWithCard.vue, edit/kubevirt.io.virtualmachine/SSHKey.vue, list/kubevirt.io.virtualmachine/MigrationModal.vue, list/kubevirt.io.virtualmachine/backupModal.vue, list/kubevirt.io.virtualmachine/cloneTemplate.vue, list/kubevirt.io.virtualmachine/restoreModal.vue, plugins/steve/actions.js, plugins/steve/resource-instance.js
https://github.com/harvester/harvester/issues/854
https://github.com/harvester/harvester/issues/815
=> update: modal sytle, fix: 854

pages/auth/login.vue, pages/auth/logout.vue, store/auth.js
https://github.com/harvester/harvester/issues/873
=> fix: not rancher mode

assets/translations/en-us.yaml, list/kubevirt.io.virtualmachine/MigrationModal.vue
fixes https://github.com/harvester/harvester/issues/906
=> fix: change migration dialog button from create to migrate

scripts/build-aws, scripts/build-embedded, scripts/build-hosted
https://github.com/harvester/harvester/issues/952
=> fix: 952 (error route in ui)

components/MessageLink.vue, config/table-headers.js, edit/harvesterhci.io.virtualmachinebackup.vue, list/harvesterhci.io.virtualmachinebackup.vue, models/harvesterhci.io.setting.js, models/harvesterhci.io.virtualmachinebackup.js
https://github.com/harvester/harvester/issues/897
=> refactor: backup list page、 fix: 897

edit/kubevirt.io.virtualmachine/network/index.vue, edit/kubevirt.io.virtualmachine/volume/type/existing.vue
[https://github.com/harvester/harvester/issues/1003](https://github.com/harvester/harvester/issues/1003)
=> user can choose volumes/vlans are not in default ns

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, components/formatter/hostName.vue, config/labels-annotations.js, detail/host/basic.vue, edit/host.vue, list/host/index.vue, models/kubevirt.io.virtualmachine.js, models/node.js
Add the `Console Url` field on Host Page, if the field is empty, the console bar on List Page will be hidden.
[https://github.com/harvester/harvester/issues/752](https://github.com/harvester/harvester/issues/752)
=> Implement Host Console

components/formatter/ipAddress.vue, list/kubevirt.io.virtualmachine/index.vue
https://github.com/harvester/harvester/issues/661
Remove id from search key
=> Fix VM page search

store/auth.js
[https://github.com/harvester/harvester/issues/1043](https://github.com/harvester/harvester/issues/1043)
=> check first-login according to management.cattle.io.setting
